from pathlib import Path

def w(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {path}")

# ── ReportPage ────────────────────────────────────────────────────────────────
w("frontend/src/pages/ReportPage.tsx", (
    "import React, { useState, useEffect } from 'react';\n"
    "import { useParams } from 'react-router-dom';\n"
    "import { generateReport, fetchReport, getReportHtmlUrl } from '../services/api';\n"
    "import { LoadingState } from '../components/StateComponents';\n\n"
    "export default function ReportPage() {\n"
    "  const { id } = useParams<{id:string}>();\n"
    "  const [report, setReport] = useState<any>(null);\n"
    "  const [loading, setLoading] = useState(false);\n"
    "  const [generating, setGenerating] = useState(false);\n\n"
    "  useEffect(() => {\n"
    "    if (!id) return; setLoading(true);\n"
    "    fetchReport(id).then(setReport).catch(()=>{}).finally(()=>setLoading(false));\n"
    "  }, [id]);\n\n"
    "  const handleGenerate = async () => {\n"
    "    if (!id) return; setGenerating(true);\n"
    "    try { const r = await generateReport(id); setReport(r); fetchReport(id).then(setReport).catch(()=>{}); }\n"
    "    finally { setGenerating(false); }\n"
    "  };\n\n"
    "  if (loading) return <LoadingState message=\"Checking for existing report...\" />;\n\n"
    "  return (\n"
    "    <div style={{display:'flex',flexDirection:'column',height:'100%',overflow:'hidden'}}>\n"
    "      <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'var(--surface-1)',flexShrink:0}}>\n"
    "        <div>\n"
    "          <div style={{fontSize:'15px',fontWeight:600}}>{id} \u2014 Investigation Report</div>\n"
    "          <div style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>Automated narrative evidence report \u2022 HTML + Structured</div>\n"
    "        </div>\n"
    "        <div style={{display:'flex',gap:8,alignItems:'center'}}>\n"
    "          <button className=\"btn btn-primary\" onClick={handleGenerate} disabled={generating}>\n"
    "            {generating ? 'Generating...' : report ? 'Regenerate Report' : 'Generate Report'}\n"
    "          </button>\n"
    "          {report && (\n"
    "            <a href={getReportHtmlUrl(id||'')} target=\"_blank\" rel=\"noopener noreferrer\" className=\"btn btn-secondary btn-sm\">\n"
    "              Open Full Report\n"
    "            </a>\n"
    "          )}\n"
    "        </div>\n"
    "      </div>\n"
    "      {report ? (\n"
    "        <div style={{flex:1,overflow:'hidden',display:'flex',flexDirection:'column'}}>\n"
    "          <div style={{padding:'8px 16px',background:'var(--surface-1)',borderBottom:'1px solid var(--border)',display:'flex',gap:12,alignItems:'center',flexShrink:0,fontSize:'12px',fontFamily:'var(--font-mono)'}}>\n"
    "            <span style={{color:'var(--text-muted)'}}>Report ID:</span>\n"
    "            <span style={{color:'var(--accent)'}}>{report.report_id}</span>\n"
    "            <span style={{color:'var(--text-muted)'}}>Generated:</span>\n"
    "            <span>{report.generated_at?.slice(0,19)} UTC</span>\n"
    "            <span style={{color:'var(--text-muted)'}}>Status:</span>\n"
    "            <span style={{color:'var(--status-success)'}}>{report.status?.toUpperCase()}</span>\n"
    "          </div>\n"
    "          <iframe\n"
    "            src={getReportHtmlUrl(id||'')}\n"
    "            style={{flex:1,border:'none',width:'100%',background:'#0B0F14'}}\n"
    "            title=\"Investigation Report\"\n"
    "          />\n"
    "        </div>\n"
    "      ) : (\n"
    "        <div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:12}}>\n"
    "          <div style={{fontSize:'24px',color:'var(--text-muted)'}}>&#x1f4c4;</div>\n"
    "          <div style={{fontSize:'15px',color:'var(--text-secondary)',fontWeight:600}}>No report generated yet</div>\n"
    "          <div style={{fontSize:'13px',color:'var(--text-muted)',maxWidth:360,textAlign:'center'}}>\n"
    "            Generate a comprehensive HTML investigation report containing all analysis results: detection metrics, hindcast origin, vessel correlation, and audit trail.\n"
    "          </div>\n"
    "          <button className=\"btn btn-primary\" onClick={handleGenerate} disabled={generating}>\n"
    "            {generating ? 'Generating...' : 'Generate Investigation Report'}\n"
    "          </button>\n"
    "          <div className=\"alert alert-warning\" style={{maxWidth:400}}>\n"
    "            <span>\u26a0</span>\n"
    "            <div style={{fontSize:'12px'}}>Ensure hindcast and attribution analysis have been run before generating the report. The report includes all completed analysis stages.</div>\n"
    "          </div>\n"
    "        </div>\n"
    "      )}\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

# ── AnalyzePage (full pipeline launcher) ──────────────────────────────────────
w("frontend/src/pages/AnalyzePage.tsx", (
    "import React, { useState, useEffect } from 'react';\n"
    "import { useNavigate } from 'react-router-dom';\n"
    "import { fetchDashboardStats, runHindcast, runForecast, runAttribution, generateReport } from '../services/api';\n"
    "import { LoadingState } from '../components/StateComponents';\n"
    "import ProcessingPipeline from '../components/ProcessingPipeline';\n\n"
    "const STEPS = ['Detection', 'Hindcast', 'Forecast', 'AIS Attribution', 'Report'];\n\n"
    "export default function AnalyzePage() {\n"
    "  const [stats, setStats] = useState<any>(null);\n"
    "  const [step, setStep] = useState(-1);\n"
    "  const [running, setRunning] = useState(false);\n"
    "  const [done, setDone] = useState<boolean[]>([]);\n"
    "  const [error, setError] = useState<string|null>(null);\n"
    "  const navigate = useNavigate();\n\n"
    "  useEffect(() => { fetchDashboardStats().then(setStats).catch(console.error); }, []);\n\n"
    "  const runFullPipeline = async () => {\n"
    "    const spillId = stats?.incidents?.[0]?.id;\n"
    "    if (!spillId) return;\n"
    "    setRunning(true); setError(null); setDone([]);\n"
    "    const completed: boolean[] = [];\n"
    "    try {\n"
    "      setStep(1); await runHindcast(spillId); completed.push(true); setDone([...completed]);\n"
    "      setStep(2); await runForecast(spillId); completed.push(true); setDone([...completed]);\n"
    "      setStep(3); await runAttribution(spillId); completed.push(true); setDone([...completed]);\n"
    "      setStep(4); await generateReport(spillId); completed.push(true); setDone([...completed]);\n"
    "      setStep(5);\n"
    "    } catch(e:any) { setError(e.message); }\n"
    "    finally { setRunning(false); }\n"
    "  };\n\n"
    "  const spillId = stats?.incidents?.[0]?.id || 'SIH-2024-001';\n"
    "  const stages = [\n"
    "    { label: 'SAR Detection & Characterization', status: 'complete' as const, detail: 'Precomputed / DEMO' },\n"
    "    { label: 'Drift Hindcast (Backward RK4)', status: (step>1||done[0])?'complete' as const:step===1?'processing' as const:'waiting' as const, detail: done[0]?'Done':'50 particles, 18h' },\n"
    "    { label: 'Drift Forecast (+48h)', status: (step>2||done[1])?'complete' as const:step===2?'processing' as const:'waiting' as const, detail: done[1]?'Done':'50 particles, 48h' },\n"
    "    { label: 'AIS Attribution Analysis', status: (step>3||done[2])?'complete' as const:step===3?'processing' as const:'waiting' as const, detail: done[2]?'Done':'7 vessels scored' },\n"
    "    { label: 'Report Generation', status: (step>4||done[3])?'complete' as const:step===4?'processing' as const:'waiting' as const, detail: done[3]?'Done':'HTML+structured' },\n"
    "  ];\n\n"
    "  return (\n"
    "    <div style={{display:'flex',flexDirection:'column',height:'100%',overflow:'auto'}}>\n"
    "      <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',background:'var(--surface-1)',flexShrink:0}}>\n"
    "        <div style={{fontSize:'15px',fontWeight:600}}>Full Pipeline Analysis</div>\n"
    "        <div style={{fontSize:'11px',color:'var(--text-muted)'}}>Run all stages sequentially: Hindcast \u2192 Forecast \u2192 Attribution \u2192 Report</div>\n"
    "      </div>\n"
    "      <div style={{maxWidth:600,margin:'0 auto',padding:24,width:'100%'}}>\n"
    "        <div style={{marginBottom:16}}>\n"
    "          <div style={{fontSize:'13px',fontWeight:600,marginBottom:4,color:'var(--text-secondary)'}}>Target Incident</div>\n"
    "          <div style={{fontFamily:'var(--font-mono)',fontSize:'14px',color:'var(--accent)',padding:'8px 12px',background:'var(--surface-1)',border:'1px solid var(--border)',borderRadius:'var(--radius)'}}>\n"
    "            {spillId}\n"
    "          </div>\n"
    "        </div>\n"
    "        <div style={{marginBottom:20}}>\n"
    "          <div style={{fontSize:'13px',fontWeight:600,marginBottom:8,color:'var(--text-secondary)'}}>Pipeline Stages</div>\n"
    "          <ProcessingPipeline stages={stages} />\n"
    "        </div>\n"
    "        {error && <div className=\"alert alert-error\" style={{marginBottom:16}}><span>\u2717</span><div>{error}</div></div>}\n"
    "        {step===5 && <div className=\"alert alert-info\" style={{marginBottom:16}}><span>\u2713</span><div style={{fontSize:'13px'}}>All pipeline stages completed.</div></div>}\n"
    "        <div style={{display:'flex',gap:8}}>\n"
    "          <button className=\"btn btn-primary\" onClick={runFullPipeline} disabled={running} style={{flex:1}}>\n"
    "            {running ? 'Running Pipeline...' : step===5 ? 'Run Pipeline Again' : 'Run Full Pipeline'}\n"
    "          </button>\n"
    "        </div>\n"
    "        {step===5 && (\n"
    "          <div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}>\n"
    "            {[['View Vessel Investigation','/incidents/'+spillId+'/vessels'],['Digital Twin','/incidents/'+spillId+'/timeline'],['Investigation Report','/incidents/'+spillId+'/report']].map(([l,p]) => (\n"
    "              <button key={p} className=\"btn btn-secondary btn-sm\" onClick={()=>navigate(p)}>{l}</button>\n"
    "            ))}\n"
    "          </div>\n"
    "        )}\n"
    "        <div style={{marginTop:20,padding:'12px',background:'var(--surface-1)',border:'1px solid var(--border)',borderRadius:'var(--radius)'}}>\n"
    "          <div style={{fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)',marginBottom:6}}>Technical Parameters</div>\n"
    "          {[['Particle Count','50'],['Integration Method','RK4'],['Hindcast','18h backward'],['Forecast','48h forward'],['Timestep','\u0394t=30 min'],['Windage','\u03b1=0.03'],['AIS Radius','50 km'],['AIS Window','\xb12 h'],['Seed','26143 (deterministic)']\n"
    "          ].map(([k,v]) => (\n"
    "            <div key={k} style={{display:'flex',justifyContent:'space-between',fontSize:'12px',padding:'2px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "              <span style={{color:'var(--text-muted)'}}>{k}</span>\n"
    "              <span style={{fontFamily:'var(--font-mono)',color:'var(--text-primary)'}}>{v}</span>\n"
    "            </div>\n"
    "          ))}\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

print("ReportPage + AnalyzePage done")
