from pathlib import Path

def w(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {path}")

# ── DigitalTwinPage (Timeline) ────────────────────────────────────────────────
w("frontend/src/pages/DigitalTwinPage.tsx", (
    "import React, { useState, useEffect, useRef, useCallback } from 'react';\n"
    "import { useParams } from 'react-router-dom';\n"
    "import { fetchSpill, fetchAllTracks, fetchAttribution } from '../services/api';\n"
    "import { useHindcast, useForecast } from '../hooks/useSpill';\n"
    "import InvestigationMap from '../map/InvestigationMap';\n"
    "import LayerControl from '../components/LayerControl';\n"
    "import { useStore } from '../state/store';\n"
    "import { LoadingState } from '../components/StateComponents';\n\n"
    "export default function DigitalTwinPage() {\n"
    "  const { id } = useParams<{id:string}>();\n"
    "  const [spill, setSpill] = useState<any>(null);\n"
    "  const [tracks, setTracks] = useState<any[]>([]);\n"
    "  const [vessels, setVessels] = useState<any[]>([]);\n"
    "  const [loading, setLoading] = useState(true);\n"
    "  const { hindcast } = useHindcast(id||null);\n"
    "  const { forecast } = useForecast(id||null);\n"
    "  const { timelinePosition, setTimelinePosition, timelinePlaying, setTimelinePlaying, timelineSpeed } = useStore();\n"
    "  const animRef = useRef<number|null>(null);\n"
    "  const prevTimeRef = useRef<number|null>(null);\n\n"
    "  useEffect(() => {\n"
    "    if (!id) return;\n"
    "    Promise.all([fetchSpill(id), fetchAllTracks(id)])\n"
    "      .then(([sp,tr]) => { setSpill(sp); setTracks(tr); })\n"
    "      .catch(console.error)\n"
    "      .finally(()=>setLoading(false));\n"
    "    fetchAttribution(id).then(a=>setVessels(a.vessels||[])).catch(()=>{});\n"
    "  }, [id]);\n\n"
    "  const animate = useCallback((ts: number) => {\n"
    "    if (prevTimeRef.current !== null) {\n"
    "      const dt = (ts - prevTimeRef.current) / 1000;\n"
    "      setTimelinePosition(p => {\n"
    "        const next = p + dt * timelineSpeed * 0.005;\n"
    "        if (next >= 1) { setTimelinePlaying(false); return 1; }\n"
    "        return next;\n"
    "      });\n"
    "    }\n"
    "    prevTimeRef.current = ts;\n"
    "    animRef.current = requestAnimationFrame(animate);\n"
    "  }, [timelineSpeed, setTimelinePosition, setTimelinePlaying]);\n\n"
    "  useEffect(() => {\n"
    "    if (timelinePlaying) {\n"
    "      prevTimeRef.current = null;\n"
    "      animRef.current = requestAnimationFrame(animate);\n"
    "    } else {\n"
    "      if (animRef.current) cancelAnimationFrame(animRef.current);\n"
    "    }\n"
    "    return () => { if (animRef.current) cancelAnimationFrame(animRef.current); };\n"
    "  }, [timelinePlaying, animate]);\n\n"
    "  if (loading) return <LoadingState message=\"Loading digital twin...\" />;\n\n"
    "  const t0 = spill?.satellite_acquisition_time ? new Date(spill.satellite_acquisition_time) : new Date();\n"
    "  const hindcastHours = hindcast?.hindcast_hours || hindcast?.integration_hours || 18;\n"
    "  const forecastHours = forecast?.forecast_hours || forecast?.integration_hours || 48;\n"
    "  const totalHours = hindcastHours + forecastHours;\n"
    "  const currentOffsetH = (timelinePosition - (hindcastHours/totalHours)) * totalHours;\n"
    "  const currentTime = new Date(t0.getTime() + currentOffsetH * 3600 * 1000);\n\n"
    "  return (\n"
    "    <div style={{display:'flex',flexDirection:'column',height:'100%',overflow:'hidden'}}>\n"
    "      <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'var(--surface-1)',flexShrink:0}}>\n"
    "        <div>\n"
    "          <div style={{fontSize:'15px',fontWeight:600}}>{id} \u2014 Digital Twin Replay</div>\n"
    "          <div style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>Hindcast + Forecast ensemble visualization &bull; All data synthetic</div>\n"
    "        </div>\n"
    "        <div style={{fontFamily:'var(--font-mono)',fontSize:'13px',color:'var(--text-secondary)'}}>\n"
    "          T: {currentTime.toISOString().slice(0,16)} UTC\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style={{flex:1,overflow:'hidden',position:'relative'}}>\n"
    "        <InvestigationMap spill={spill} hindcast={hindcast} forecast={forecast} tracks={tracks} attributions={vessels} timelineStep={timelinePosition}>\n"
    "          <LayerControl />\n"
    "        </InvestigationMap>\n"
    "      </div>\n"
    "      {/* Timeline bar */}\n"
    "      <div className=\"timeline-bar\" style={{flexShrink:0}}>\n"
    "        <div className=\"timeline-controls\">\n"
    "          <button className=\"btn btn-secondary btn-sm\" onClick={()=>setTimelinePosition(0)}>|&lt;</button>\n"
    "          <button className=\"btn btn-secondary btn-sm\" onClick={()=>setTimelinePosition(p=>Math.max(0,p-0.05))}>&lt;</button>\n"
    "          <button className=\"btn btn-primary btn-sm\" onClick={()=>setTimelinePlaying(!timelinePlaying)} style={{minWidth:64}}>\n"
    "            {timelinePlaying ? '\u23f8 Pause' : '\u25b6 Play'}\n"
    "          </button>\n"
    "          <button className=\"btn btn-secondary btn-sm\" onClick={()=>setTimelinePosition(p=>Math.min(1,p+0.05))}>&gt;</button>\n"
    "          <button className=\"btn btn-secondary btn-sm\" onClick={()=>setTimelinePosition(1)}>&gt;|</button>\n"
    "          <input type=\"range\" min=\"0\" max=\"1\" step=\"0.001\" value={timelinePosition} onChange={e=>setTimelinePosition(parseFloat(e.target.value))} className=\"timeline-scrubber\" />\n"
    "          <span className=\"timeline-current-time\">{currentTime.toISOString().slice(0,16)} UTC</span>\n"
    "          <span style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)',whiteSpace:'nowrap'}}>Speed: 1x</span>\n"
    "        </div>\n"
    "        <div className=\"timeline-markers\">\n"
    "          <span>T-{hindcastHours}h (Hindcast start)</span>\n"
    "          <span>T-0 (SAR Acquisition)</span>\n"
    "          <span>T+{forecastHours}h (Forecast end)</span>\n"
    "        </div>\n"
    "        <div style={{fontSize:'10px',color:'var(--text-disabled)',fontFamily:'var(--font-mono)'}}>\n"
    "          DIGITAL TWIN &mdash; Synthetic simulation, seed=26143. Not operational. For demonstration only.\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

print("DigitalTwinPage done")
