from pathlib import Path

def w(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {path}")

w("frontend/src/map/InvestigationMap.tsx", (
    "import React, { useRef, useEffect, useState, useCallback } from 'react';\n"
    "import maplibregl from 'maplibre-gl';\n"
    "import 'maplibre-gl/dist/maplibre-gl.css';\n"
    "import { useStore } from '../state/store';\n"
    "import type { OilSpill, HindcastResult, ForecastResult, VesselTrack, Attribution } from '../types';\n\n"
    "const MAP_STYLE = {\n"
    "  version: 8 as const,\n"
    "  sources: {\n"
    "    osm: { type: 'raster' as const, tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'], tileSize: 256, attribution: '(c) OpenStreetMap contributors' }\n"
    "  },\n"
    "  layers: [\n"
    "    { id: 'osm', type: 'raster' as const, source: 'osm', paint: { 'raster-opacity': 0.3, 'raster-brightness-min': 0, 'raster-brightness-max': 0.2, 'raster-saturation': -1, 'raster-contrast': 0.1 } }\n"
    "  ]\n"
    "};\n\n"
    "interface InvestigationMapProps {\n"
    "  spill?: OilSpill | null;\n"
    "  hindcast?: HindcastResult | null;\n"
    "  forecast?: ForecastResult | null;\n"
    "  tracks?: VesselTrack[];\n"
    "  attributions?: Attribution[];\n"
    "  selectedMmsi?: string | null;\n"
    "  timelineStep?: number;\n"
    "  onVesselClick?: (mmsi: string) => void;\n"
    "  onSpillClick?: () => void;\n"
    "  children?: React.ReactNode;\n"
    "}\n\n"
    "export default function InvestigationMap({\n"
    "  spill, hindcast, forecast, tracks, attributions, selectedMmsi, timelineStep, onVesselClick, onSpillClick, children\n"
    "}: InvestigationMapProps) {\n"
    "  const mapContainer = useRef<HTMLDivElement>(null);\n"
    "  const map = useRef<maplibregl.Map | null>(null);\n"
    "  const { layers } = useStore();\n"
    "  const [coords, setCoords] = useState({ lat: 0, lon: 0 });\n\n"
    "  useEffect(() => {\n"
    "    if (!mapContainer.current || map.current) return;\n"
    "    map.current = new maplibregl.Map({\n"
    "      container: mapContainer.current,\n"
    "      style: MAP_STYLE,\n"
    "      center: [72.68, 15.42],\n"
    "      zoom: 7.5,\n"
    "      minZoom: 3,\n"
    "      maxZoom: 16,\n"
    "    });\n"
    "    const m = map.current;\n"
    "    m.addControl(new maplibregl.NavigationControl({ showCompass: true }), 'top-left');\n"
    "    m.addControl(new maplibregl.ScaleControl({ maxWidth: 100, unit: 'metric' }), 'bottom-right');\n"
    "    m.on('mousemove', (e) => setCoords({ lat: e.lngLat.lat, lon: e.lngLat.lng }));\n"
    "    m.on('load', () => addDataLayers(m));\n"
    "    return () => { m.remove(); map.current = null; };\n"
    "  }, []);\n\n"
    "  const addDataLayers = (m: maplibregl.Map) => {\n"
    "    // Spill polygon source\n"
    "    if (!m.getSource('spill-src')) {\n"
    "      m.addSource('spill-src', { type: 'geojson', data: { type: 'FeatureCollection', features: [] } });\n"
    "      m.addLayer({ id: 'spill-fill', type: 'fill', source: 'spill-src', paint: { 'fill-color': '#F59E0B', 'fill-opacity': 0.28 } });\n"
    "      m.addLayer({ id: 'spill-line', type: 'line', source: 'spill-src', paint: { 'line-color': '#FFB020', 'line-width': 2 } });\n"
    "    }\n"
    "    // Origin region\n"
    "    if (!m.getSource('origin-src')) {\n"
    "      m.addSource('origin-src', { type: 'geojson', data: { type: 'FeatureCollection', features: [] } });\n"
    "      m.addLayer({ id: 'origin-fill', type: 'fill', source: 'origin-src', paint: { 'fill-color': '#7C8FA6', 'fill-opacity': 0.22 } });\n"
    "      m.addLayer({ id: 'origin-line', type: 'line', source: 'origin-src', paint: { 'line-color': '#8FA3B8', 'line-width': 1.5, 'line-dasharray': [3, 2] } });\n"
    "    }\n"
    "    // Hindcast particles\n"
    "    if (!m.getSource('hindcast-src')) {\n"
    "      m.addSource('hindcast-src', { type: 'geojson', data: { type: 'FeatureCollection', features: [] } });\n"
    "      m.addLayer({ id: 'hindcast-pts', type: 'circle', source: 'hindcast-src', paint: { 'circle-radius': 2, 'circle-color': '#6F879C', 'circle-opacity': 0.5 } });\n"
    "    }\n"
    "    // Forecast particles\n"
    "    if (!m.getSource('forecast-src')) {\n"
    "      m.addSource('forecast-src', { type: 'geojson', data: { type: 'FeatureCollection', features: [] } });\n"
    "      m.addLayer({ id: 'forecast-pts', type: 'circle', source: 'forecast-src', paint: { 'circle-radius': 2, 'circle-color': '#A8B7C5', 'circle-opacity': 0.5 } });\n"
    "    }\n"
    "    // Vessel tracks\n"
    "    if (!m.getSource('tracks-src')) {\n"
    "      m.addSource('tracks-src', { type: 'geojson', data: { type: 'FeatureCollection', features: [] } });\n"
    "      m.addLayer({ id: 'tracks-line', type: 'line', source: 'tracks-src', paint: { 'line-color': ['get','color'], 'line-width': 1.5, 'line-opacity': 0.7 } });\n"
    "    }\n"
    "    // Vessel points\n"
    "    if (!m.getSource('vessels-src')) {\n"
    "      m.addSource('vessels-src', { type: 'geojson', data: { type: 'FeatureCollection', features: [] } });\n"
    "      m.addLayer({ id: 'vessels-pts', type: 'circle', source: 'vessels-src',\n"
    "        paint: { 'circle-radius': ['case',['get','isCandidate'],8,5], 'circle-color': ['get','color'],\n"
    "                 'circle-stroke-width': ['case',['get','isSelected'],3,1], 'circle-stroke-color': '#E6EAEE', 'circle-opacity': 0.9 } });\n"
    "      m.on('click', 'vessels-pts', (e) => {\n"
    "        const f = e.features?.[0]; if (!f) return;\n"
    "        const mmsi = f.properties?.mmsi; if (mmsi && onVesselClick) onVesselClick(mmsi);\n"
    "      });\n"
    "    }\n"
    "    // Centroid marker\n"
    "    if (!m.getSource('centroid-src')) {\n"
    "      m.addSource('centroid-src', { type: 'geojson', data: { type: 'FeatureCollection', features: [] } });\n"
    "      m.addLayer({ id: 'centroid-pt', type: 'circle', source: 'centroid-src', paint: { 'circle-radius': 6, 'circle-color': '#F97316', 'circle-stroke-width': 2, 'circle-stroke-color': '#fff' } });\n"
    "    }\n"
    "  };\n\n"
    "  // Update spill layer\n"
    "  useEffect(() => {\n"
    "    const m = map.current; if (!m || !m.isStyleLoaded()) return;\n"
    "    const src = m.getSource('spill-src') as maplibregl.GeoJSONSource;\n"
    "    if (!src) return;\n"
    "    const features = [];\n"
    "    if (spill?.spill_polygon_geojson && layers.slickGeometry) {\n"
    "      features.push({ type: 'Feature', geometry: spill.spill_polygon_geojson, properties: { provenance: spill.provenance } });\n"
    "    }\n"
    "    src.setData({ type: 'FeatureCollection', features } as any);\n"
    "    const centSrc = m.getSource('centroid-src') as maplibregl.GeoJSONSource;\n"
    "    if (centSrc && spill?.centroid_geojson) {\n"
    "      centSrc.setData({ type: 'FeatureCollection', features: [{ type: 'Feature', geometry: spill.centroid_geojson, properties: {} }] } as any);\n"
    "    }\n"
    "  }, [spill, layers.slickGeometry]);\n\n"
    "  // Update origin region\n"
    "  useEffect(() => {\n"
    "    const m = map.current; if (!m || !m.isStyleLoaded()) return;\n"
    "    const src = m.getSource('origin-src') as maplibregl.GeoJSONSource;\n"
    "    if (!src) return;\n"
    "    const features = hindcast?.origin_region_geojson && layers.originRegion\n"
    "      ? [{ type: 'Feature', geometry: hindcast.origin_region_geojson, properties: {} }] : [];\n"
    "    src.setData({ type: 'FeatureCollection', features } as any);\n"
    "  }, [hindcast, layers.originRegion]);\n\n"
    "  // Update hindcast particles\n"
    "  useEffect(() => {\n"
    "    const m = map.current; if (!m || !m.isStyleLoaded()) return;\n"
    "    const src = m.getSource('hindcast-src') as maplibregl.GeoJSONSource;\n"
    "    if (!src || !hindcast?.particles || !layers.hindcast) { src?.setData({ type: 'FeatureCollection', features: [] } as any); return; }\n"
    "    const step = timelineStep ?? -(hindcast.particles[0]?.trajectory?.length - 1);\n"
    "    const features = hindcast.particles.slice(0, 100).map(p => {\n"
    "      const pos = p.trajectory[p.trajectory.length - 1];\n"
    "      return { type: 'Feature', geometry: { type: 'Point', coordinates: [pos.lon, pos.lat] }, properties: { pid: p.particle_id } };\n"
    "    });\n"
    "    src.setData({ type: 'FeatureCollection', features } as any);\n"
    "  }, [hindcast, layers.hindcast, timelineStep]);\n\n"
    "  // Update forecast particles\n"
    "  useEffect(() => {\n"
    "    const m = map.current; if (!m || !m.isStyleLoaded()) return;\n"
    "    const src = m.getSource('forecast-src') as maplibregl.GeoJSONSource;\n"
    "    if (!src || !forecast?.particles || !layers.forecast) { src?.setData({ type: 'FeatureCollection', features: [] } as any); return; }\n"
    "    const features = forecast.particles.slice(0, 100).map(p => {\n"
    "      const idx = Math.min(Math.floor((timelineStep ?? 0.5) * p.trajectory.length), p.trajectory.length - 1);\n"
    "      const pos = p.trajectory[Math.max(0, idx)];\n"
    "      return { type: 'Feature', geometry: { type: 'Point', coordinates: [pos.lon, pos.lat] }, properties: { pid: p.particle_id } };\n"
    "    });\n"
    "    src.setData({ type: 'FeatureCollection', features } as any);\n"
    "  }, [forecast, layers.forecast, timelineStep]);\n\n"
    "  // Update vessel tracks + points\n"
    "  useEffect(() => {\n"
    "    const m = map.current; if (!m || !m.isStyleLoaded()) return;\n"
    "    const trackSrc = m.getSource('tracks-src') as maplibregl.GeoJSONSource;\n"
    "    const vesselSrc = m.getSource('vessels-src') as maplibregl.GeoJSONSource;\n"
    "    if (!trackSrc || !vesselSrc) return;\n"
    "    const candidateMmsis = new Set(attributions?.slice(0,3).map(a=>a.mmsi)||[]);\n"
    "    const trackFeatures: any[] = [];\n"
    "    const vesselFeatures: any[] = [];\n"
    "    (tracks||[]).forEach(t => {\n"
    "      const isCandidate = candidateMmsis.has(t.mmsi);\n"
    "      const isSelected = t.mmsi === selectedMmsi;\n"
    "      const color = isSelected ? '#3FA7D6' : isCandidate ? '#D97706' : '#59636E';\n"
    "      if (layers.vesselTracks && t.track_geojson) {\n"
    "        trackFeatures.push({ type: 'Feature', geometry: t.track_geojson, properties: { mmsi: t.mmsi, color, isCandidate, isSelected } });\n"
    "      }\n"
    "      if (layers.aisVessels && t.track_geojson?.coordinates?.length) {\n"
    "        const coords = t.track_geojson.coordinates;\n"
    "        const midIdx = Math.floor(coords.length / 2);\n"
    "        const midPt = coords[midIdx];\n"
    "        vesselFeatures.push({ type: 'Feature', geometry: { type: 'Point', coordinates: midPt }, properties: { mmsi: t.mmsi, vessel_name: t.vessel_name || t.mmsi, color, isCandidate, isSelected } });\n"
    "      }\n"
    "    });\n"
    "    trackSrc.setData({ type: 'FeatureCollection', features: trackFeatures } as any);\n"
    "    vesselSrc.setData({ type: 'FeatureCollection', features: vesselFeatures } as any);\n"
    "  }, [tracks, attributions, selectedMmsi, layers.vesselTracks, layers.aisVessels]);\n\n"
    "  return (\n"
    "    <div className=\"map-container\">\n"
    "      <div ref={mapContainer} className=\"map-gl\" />\n"
    "      <div className=\"coord-display\">Lat {coords.lat.toFixed(5)} &nbsp; Lon {coords.lon.toFixed(5)}</div>\n"
    "      {children}\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

print("InvestigationMap done")
