from pathlib import Path

def w(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {path}")

# ── ForecastPage ──────────────────────────────────────────────────────────────
w("frontend/src/pages/ForecastPage.tsx", (
    "import React, { useState, useEffect } from 'react';\n"
    "import { useParams } from 'react-router-dom';\n"
    "import { fetchSpill, runForecast } from '../services/api';\n"
    "import { useForecast } from '../hooks/useSpill';\n"
    "import InvestigationMap from '../map/InvestigationMap';\n"
    "import LayerControl from '../components/LayerControl';\n"
    "import ProvenanceBadge from '../components/ProvenanceBadge';\n"
    "import { LoadingState, UnavailableState } from '../components/StateComponents';\n\n"
    "export default function ForecastPage() {\n"
    "  const { id } = useParams<{id:string}>();\n"
    "  const [spill, setSpill] = useState<any>(null);\n"
    "  const [running, setRunning] = useState(false);\n"
    "  const { forecast, loading, refetch } = useForecast(id||null);\n\n"
    "  useEffect(() => { if (!id) return; fetchSpill(id).then(setSpill).catch(console.error); }, [id]);\n\n"
    "  const handleRun = async () => {\n"
    "    if (!id) return; setRunning(true);\n"
    "    try { await runForecast(id); refetch(); } finally { setRunning(false); }\n"
    "  };\n\n"
    "  return (\n"
    "    <div style={{display:'flex',flexDirection:'column',height:'100%',overflow:'hidden'}}>\n"
    "      <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'var(--surface-1)',flexShrink:0}}>\n"
    "        <div>\n"
    "          <div style={{fontSize:'15px',fontWeight:600}}>{id} \u2014 Drift Forecast</div>\n"
    "          <div style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>Forward particle integration \u2022 RK4 \u2022 +48h ensemble</div>\n"
    "        </div>\n"
    "        <div style={{display:'flex',gap:8,alignItems:'center'}}>\n"
    "          {!forecast && !loading && (\n"
    "            <button className=\"btn btn-primary\" onClick={handleRun} disabled={running}>\n"
    "              {running ? 'Running...' : 'Run Forecast'}\n"
    "            </button>\n"
    "          )}\n"
    "          <ProvenanceBadge provenance=\"predicted\" />\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style={{display:'grid',gridTemplateColumns:'1fr 300px',flex:1,overflow:'hidden'}}>\n"
    "        {loading ? <LoadingState message=\"Loading forecast...\" /> : (\n"
    "          <InvestigationMap spill={spill} forecast={forecast}>\n"
    "            <LayerControl />\n"
    "          </InvestigationMap>\n"
    "        )}\n"
    "        <div style={{borderLeft:'1px solid var(--border)',background:'var(--bg-secondary)',overflow:'auto'}}>\n"
    "          <div style={{padding:'10px 12px',borderBottom:'1px solid var(--border)',fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)'}}>Forecast Horizons</div>\n"
    "          {forecast ? (\n"
    "            <div style={{padding:12}}>\n"
    "              <div className=\"alert alert-warning\" style={{marginBottom:12}}>\n"
    "                <span>\u26a0</span>\n"
    "                <div style={{fontSize:'12px'}}>Forecast is based on synthetic environmental data. Accuracy degrades beyond 24h. Not for operational use.</div>\n"
    "              </div>\n"
    "              {Object.entries(forecast.horizon_stats||{}).map(([h,st]: [string,any]) => (\n"
    "                <div key={h} style={{background:'var(--surface-1)',border:'1px solid var(--border)',borderRadius:'var(--radius)',padding:'10px',marginBottom:8}}>\n"
    "                  <div style={{fontSize:'14px',fontFamily:'var(--font-mono)',fontWeight:600,color:'var(--predicted)',marginBottom:6}}>{h}</div>\n"
    "                  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:4,fontSize:'12px'}}>\n"
    "                    <span style={{color:'var(--text-muted)'}}>Centroid</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)'}}>{st.centroid_lat?.toFixed(4)}, {st.centroid_lon?.toFixed(4)}</span>\n"
    "                    <span style={{color:'var(--text-muted)'}}>Spread</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)'}}>{st.spread_km?.toFixed(2)} km</span>\n"
    "                    <span style={{color:'var(--text-muted)'}}>Particles</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)'}}>{st.particle_count}</span>\n"
    "                  </div>\n"
    "                </div>\n"
    "              ))}\n"
    "              <div style={{fontSize:'11px',color:'var(--text-muted)',marginTop:8}}>\n"
    "                Particles: {forecast.particle_count} | Method: {forecast.integration_method} | \u0394t: {forecast.timestep_min} min\n"
    "              </div>\n"
    "            </div>\n"
    "          ) : (\n"
    "            <div style={{padding:16}}>\n"
    "              <UnavailableState title=\"No Forecast\" message=\"Click 'Run Forecast' to project the spill forward 48h.\" />\n"
    "            </div>\n"
    "          )}\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

# ── VesselInvestigationPage ───────────────────────────────────────────────────
w("frontend/src/pages/VesselInvestigationPage.tsx", (
    "import React, { useState, useEffect, useCallback } from 'react';\n"
    "import { useParams } from 'react-router-dom';\n"
    "import { fetchSpill, runAttribution, fetchAttribution, fetchAllTracks, runHindcast } from '../services/api';\n"
    "import InvestigationMap from '../map/InvestigationMap';\n"
    "import LayerControl from '../components/LayerControl';\n"
    "import EvidenceBar from '../components/EvidenceBar';\n"
    "import FilteringFunnel from '../components/FilteringFunnel';\n"
    "import ProvenanceBadge from '../components/ProvenanceBadge';\n"
    "import { LoadingState, ErrorState, UnavailableState } from '../components/StateComponents';\n"
    "import { useStore } from '../state/store';\n\n"
    "export default function VesselInvestigationPage() {\n"
    "  const { id } = useParams<{id:string}>();\n"
    "  const [spill, setSpill] = useState<any>(null);\n"
    "  const [attribution, setAttribution] = useState<any>(null);\n"
    "  const [funnel, setFunnel] = useState<any>(null);\n"
    "  const [tracks, setTracks] = useState<any[]>([]);\n"
    "  const [loading, setLoading] = useState(true);\n"
    "  const [running, setRunning] = useState(false);\n"
    "  const [activeIdx, setActiveIdx] = useState(0);\n"
    "  const [tab, setTab] = useState<'rank'|'funnel'|'evidence'>('rank');\n"
    "  const { selectedMmsi, setSelectedMmsi } = useStore();\n\n"
    "  const loadData = useCallback(async () => {\n"
    "    if (!id) return;\n"
    "    setLoading(true);\n"
    "    try {\n"
    "      const [sp, tr] = await Promise.all([fetchSpill(id), fetchAllTracks(id)]);\n"
    "      setSpill(sp); setTracks(tr);\n"
    "      try { const a = await fetchAttribution(id); setAttribution(a); } catch(e) { /* none yet */ }\n"
    "    } finally { setLoading(false); }\n"
    "  }, [id]);\n\n"
    "  useEffect(() => { loadData(); }, [loadData]);\n\n"
    "  const handleRunAttribution = async () => {\n"
    "    if (!id) return; setRunning(true);\n"
    "    try {\n"
    "      try { await runHindcast(id); } catch(e) { /* might exist */ }\n"
    "      const f = await runAttribution(id); setFunnel(f); await loadData();\n"
    "    } finally { setRunning(false); }\n"
    "  };\n\n"
    "  if (loading) return <LoadingState message=\"Loading vessel investigation...\" />;\n\n"
    "  const vessels = attribution?.vessels || funnel?.vessels || [];\n"
    "  const topVessel = vessels[activeIdx];\n"
    "  const funnelStages = funnel ? [\n"
    "    { label: 'All AIS Observations', count: funnel.total_ais_observations || 0 },\n"
    "    { label: 'Spatial Filter', count: funnel.spatial_filter?.output_count || 0, removed: funnel.spatial_filter?.removed_count, config: funnel.spatial_filter?.radius_km+'km radius' },\n"
    "    { label: 'Temporal Filter', count: funnel.temporal_filter?.output_count || 0, removed: funnel.temporal_filter?.removed_count, config: '\xb1'+funnel.temporal_filter?.window_hours+'h window' },\n"
    "    { label: 'Trajectory Filter', count: funnel.trajectory_filter?.output_count || 0, removed: funnel.trajectory_filter?.removed_count, config: 'heading compatible', active: true },\n"
    "    { label: 'Behaviour Analysis', count: funnel.behaviour_analysis_count || 0 },\n"
    "    { label: 'Ranked Candidates', count: funnel.ranked_candidates || 0 },\n"
    "  ] : [];\n\n"
    "  return (\n"
    "    <div style={{display:'flex',flexDirection:'column',height:'100%',overflow:'hidden'}}>\n"
    "      <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'var(--surface-1)',flexShrink:0}}>\n"
    "        <div>\n"
    "          <div style={{fontSize:'15px',fontWeight:600}}>{id} \u2014 Vessel Investigation</div>\n"
    "          <div style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>AIS correlation \u2022 Multi-factor scoring \u2022 Ranked candidates</div>\n"
    "        </div>\n"
    "        <div style={{display:'flex',gap:8,alignItems:'center'}}>\n"
    "          <button className=\"btn btn-primary\" onClick={handleRunAttribution} disabled={running}>\n"
    "            {running ? 'Analyzing...' : vessels.length ? 'Re-run Attribution' : 'Run Attribution Analysis'}\n"
    "          </button>\n"
    "          <ProvenanceBadge provenance=\"synthetic\" />\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style={{display:'grid',gridTemplateColumns:'260px 1fr 380px',flex:1,overflow:'hidden'}}>\n"
    "        {/* Left: Vessel ranking table */}\n"
    "        <div style={{borderRight:'1px solid var(--border)',background:'var(--bg-secondary)',display:'flex',flexDirection:'column',overflow:'hidden'}}>\n"
    "          <div style={{display:'flex',gap:0,flexShrink:0,borderBottom:'1px solid var(--border)'}}>\n"
    "            {['rank','funnel','evidence'].map(t => (\n"
    "              <button key={t} onClick={()=>setTab(t as any)}\n"
    "                style={{flex:1,padding:'8px 4px',fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.05em',\n"
    "                  background:tab===t?'var(--surface-3)':'transparent',color:tab===t?'var(--accent)':'var(--text-muted)',\n"
    "                  borderBottom:tab===t?'2px solid var(--accent)':'2px solid transparent',borderTop:'none',borderLeft:'none',borderRight:'none'}}>\n"
    "                {t}\n"
    "              </button>\n"
    "            ))}\n"
    "          </div>\n"
    "          <div style={{flex:1,overflow:'auto',padding:tab==='funnel'?12:0}}>\n"
    "            {tab==='rank' && (\n"
    "              vessels.length>0 ? vessels.map((v:any,i:number)=>(\n"
    "                <div key={v.mmsi} onClick={()=>{setActiveIdx(i);setSelectedMmsi(v.mmsi);}}\n"
    "                  style={{padding:'10px 12px',borderBottom:'1px solid var(--border)',cursor:'pointer',\n"
    "                    background:selectedMmsi===v.mmsi?'var(--accent-dim)':'transparent',\n"
    "                    borderLeft:selectedMmsi===v.mmsi?'2px solid var(--accent)':'2px solid transparent'}}>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:4}}>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'13px',color:i===0?'var(--corr-high)':i===1?'var(--corr-med-high)':'var(--text-muted)'}}>\n"
    "                      #{v.rank}\n"
    "                    </span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'15px',fontWeight:600,color:i===0?'var(--oil)':'var(--text-secondary)'}}>\n"
    "                      {(v.final_score*100).toFixed(1)}\n"
    "                    </span>\n"
    "                  </div>\n"
    "                  <div style={{fontSize:'12px',fontWeight:600,color:'var(--text-primary)',marginBottom:2}}>{v.vessel_name||v.mmsi}</div>\n"
    "                  <div style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>\n"
    "                    {v.vessel_type} \u2022 MMSI {v.mmsi} \u2022 {v.flag}\n"
    "                  </div>\n"
    "                  <div style={{display:'flex',gap:8,marginTop:4}}>\n"
    "                    <span style={{fontSize:'10px',fontFamily:'var(--font-mono)',color:'var(--text-muted)'}}>evid: {v.evidence_score?.toFixed(3)}</span>\n"
    "                    <span style={{fontSize:'10px',fontFamily:'var(--font-mono)',color:'var(--text-muted)'}}>conf: {v.data_confidence?.toFixed(3)}</span>\n"
    "                  </div>\n"
    "                </div>\n"
    "              )) : <UnavailableState title=\"No analysis\" message=\"Run attribution to see ranked vessels\" />\n"
    "            )}\n"
    "            {tab==='funnel' && (\n"
    "              funnelStages.length>0 ? <FilteringFunnel stages={funnelStages} /> : <UnavailableState title=\"No funnel\" message=\"Run attribution first\" />\n"
    "            )}\n"
    "            {tab==='evidence' && topVessel && (\n"
    "              <div style={{padding:12}}>\n"
    "                <div style={{marginBottom:10,fontSize:'13px',fontWeight:600,color:'var(--text-primary)'}}>{topVessel.vessel_name}</div>\n"
    "                {(topVessel.factors||[]).map((f:any) => (\n"
    "                  <EvidenceBar key={f.factor} label={f.label} rawValue={f.raw_value} rawUnit={f.raw_unit}\n"
    "                    normalized={f.normalized} weight={f.weight} contribution={f.contribution} />\n"
    "                ))}\n"
    "              </div>\n"
    "            )}\n"
    "          </div>\n"
    "        </div>\n"
    "        {/* Center: Map */}\n"
    "        <InvestigationMap spill={spill} tracks={tracks} attributions={vessels} selectedMmsi={selectedMmsi} onVesselClick={setSelectedMmsi}>\n"
    "          <LayerControl />\n"
    "        </InvestigationMap>\n"
    "        {/* Right: Detail panel */}\n"
    "        <div style={{borderLeft:'1px solid var(--border)',background:'var(--bg-secondary)',overflow:'auto'}}>\n"
    "          {topVessel ? (\n"
    "            <div>\n"
    "              <div style={{padding:'10px 12px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between'}}>\n"
    "                <div style={{fontSize:'12px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.05em',color:'var(--text-muted)'}}>Vessel Detail</div>\n"
    "                <span style={{fontFamily:'var(--font-mono)',fontSize:'20px',fontWeight:700,color:'var(--oil)'}}>{(topVessel.final_score*100).toFixed(1)}</span>\n"
    "              </div>\n"
    "              <div style={{padding:12}}>\n"
    "                <div className=\"alert alert-warning\" style={{marginBottom:12}}>\n"
    "                  <span>\u26a0</span>\n"
    "                  <div style={{fontSize:'12px'}}>Scores are investigative correlation indicators. They do not constitute legal attribution of responsibility for this spill.</div>\n"
    "                </div>\n"
    "                {[\n"
    "                  ['Vessel Name', topVessel.vessel_name||'\u2014'],\n"
    "                  ['MMSI', topVessel.mmsi],\n"
    "                  ['IMO', topVessel.imo||'\u2014'],\n"
    "                  ['Type', topVessel.vessel_type||'\u2014'],\n"
    "                  ['Flag', topVessel.flag||'\u2014'],\n"
    "                  ['Length', topVessel.length_m ? topVessel.length_m+'m' : '\u2014'],\n"
    "                  ['GRT', topVessel.gross_tonnage ? topVessel.gross_tonnage?.toLocaleString()+' GT' : '\u2014'],\n"
    "                  ['Rank', '#'+topVessel.rank],\n"
    "                  ['Evidence Score', topVessel.evidence_score?.toFixed(4)],\n"
    "                  ['Data Confidence', topVessel.data_confidence?.toFixed(4)],\n"
    "                  ['Final Score', topVessel.final_score?.toFixed(4)],\n"
    "                  ['Distance to Origin', topVessel.distance_km?.toFixed(2)+' km'],\n"
    "                  ['Temporal Delta', topVessel.time_delta_h?.toFixed(2)+' h'],\n"
    "                  ['AIS Coverage', topVessel.ais_coverage_pct?.toFixed(1)+'%'],\n"
    "                  ['AIS Gap Detected', topVessel.ais_gap_detected ? 'YES (\u26a0)' : 'No'],\n"
    "                  ['Slowdown Observed', topVessel.slowdown_observed ? 'YES' : 'No'],\n"
    "                ].map(([k,v]) => (\n"
    "                  <div key={k} style={{display:'flex',justifyContent:'space-between',padding:'4px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>{k}</span>\n"
    "                    <span style={{fontSize:'12px',fontFamily:'var(--font-mono)',color: String(v).includes('\u26a0')||String(v).includes('YES')?'var(--status-warning)':'var(--text-primary)'}}>{v}</span>\n"
    "                  </div>\n"
    "                ))}\n"
    "                {topVessel.behaviour_observations?.length>0 && (\n"
    "                  <div style={{marginTop:12}}>\n"
    "                    <div style={{fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)',marginBottom:6}}>Behaviour Observations</div>\n"
    "                    {topVessel.behaviour_observations.map((obs:string,i:number) => (\n"
    "                      <div key={i} style={{fontSize:'12px',color:'var(--status-warning)',padding:'4px 0',borderBottom:'1px solid var(--border)'}}>\u2022 {obs}</div>\n"
    "                    ))}\n"
    "                  </div>\n"
    "                )}\n"
    "              </div>\n"
    "            </div>\n"
    "          ) : <UnavailableState title=\"Select a vessel\" message=\"Run attribution and click a vessel from the ranking list\" />}\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

print("ForecastPage + VesselInvestigationPage done")
