from pathlib import Path

def w(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {path}")

# ── CommandCenter page ────────────────────────────────────────────────────────
w("frontend/src/pages/CommandCenter.tsx", (
    "import React, { useEffect, useState } from 'react';\n"
    "import { useNavigate } from 'react-router-dom';\n"
    "import { fetchDashboardStats } from '../services/api';\n"
    "import { useStore } from '../state/store';\n"
    "import KpiStrip from '../components/KpiStrip';\n"
    "import InvestigationMap from '../map/InvestigationMap';\n"
    "import LayerControl from '../components/LayerControl';\n"
    "import { LoadingState, ErrorState } from '../components/StateComponents';\n"
    "import ProvenanceBadge from '../components/ProvenanceBadge';\n\n"
    "export default function CommandCenter() {\n"
    "  const [stats, setStats] = useState<any>(null);\n"
    "  const [loading, setLoading] = useState(true);\n"
    "  const [error, setError] = useState<string|null>(null);\n"
    "  const { setSelectedSpillId } = useStore();\n"
    "  const navigate = useNavigate();\n\n"
    "  useEffect(() => {\n"
    "    fetchDashboardStats().then(setStats).catch(e=>setError(e.message)).finally(()=>setLoading(false));\n"
    "  }, []);\n\n"
    "  if (loading) return <LoadingState message=\"Loading command center...\" />;\n"
    "  if (error) return <ErrorState message={error} onRetry={()=>{ setLoading(true); setError(null); fetchDashboardStats().then(setStats).catch(e=>setError(e.message)).finally(()=>setLoading(false));}} />;\n\n"
    "  const incidents = stats?.incidents || [];\n\n"
    "  return (\n"
    "    <div style={{display:'flex',flexDirection:'column',height:'100%',overflow:'hidden'}}>\n"
    "      <KpiStrip activeIncidents={stats?.active_incidents||0} analyzedScenes={stats?.analyzed_scenes||0}\n"
    "        analyzedVessels={stats?.analyzed_vessels||0} highPriority={stats?.high_priority_cases||0} />\n"
    "      <div style={{display:'grid',gridTemplateColumns:'260px 1fr 320px',flex:1,overflow:'hidden'}}>\n"
    "        {/* Left: Incident list */}\n"
    "        <div style={{borderRight:'1px solid var(--border)',background:'var(--bg-secondary)',overflow:'auto'}}>\n"
    "          <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)'}}>\n"
    "            Active Incidents\n"
    "          </div>\n"
    "          {incidents.map((inc: any) => (\n"
    "            <div key={inc.id} onClick={()=>{ setSelectedSpillId(inc.id); navigate('/incidents/'+inc.id);}}\n"
    "              style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',cursor:'pointer',transition:'background 150ms'}}\n"
    "              onMouseEnter={e=>(e.currentTarget.style.background='var(--surface-2)')}\n"
    "              onMouseLeave={e=>(e.currentTarget.style.background='transparent')}>\n"
    "              <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:4}}>\n"
    "                <span style={{fontFamily:'var(--font-mono)',fontSize:'12px',color:'var(--accent)'}}>{inc.id}</span>\n"
    "                <ProvenanceBadge provenance={inc.provenance} />\n"
    "              </div>\n"
    "              <div style={{fontSize:'12px',color:'var(--text-secondary)',marginBottom:2}}>{inc.incident_name}</div>\n"
    "              <div style={{display:'flex',gap:8,fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>\n"
    "                <span>{inc.area_km2?.toFixed(2)} km\xb2</span>\n"
    "                <span>conf: {inc.detection_confidence?.toFixed(3)}</span>\n"
    "                <span style={{color: inc.severity==='high'?'var(--status-error)':'var(--status-warning)'}}>{inc.severity?.toUpperCase()}</span>\n"
    "              </div>\n"
    "              <div style={{fontSize:'10px',color:'var(--text-disabled)',marginTop:2,fontFamily:'var(--font-mono)'}}>\n"
    "                T0: {inc.satellite_acquisition_time?.slice(0,16)} UTC\n"
    "              </div>\n"
    "            </div>\n"
    "          ))}\n"
    "          {incidents.length===0 && <div style={{padding:16,fontSize:'12px',color:'var(--text-muted)'}}>No incidents found</div>}\n"
    "        </div>\n"
    "        {/* Center: Map */}\n"
    "        <InvestigationMap spill={incidents[0]} >\n"
    "          <LayerControl />\n"
    "        </InvestigationMap>\n"
    "        {/* Right: Evidence panel */}\n"
    "        <div style={{borderLeft:'1px solid var(--border)',background:'var(--bg-secondary)',overflow:'auto',padding:0}}>\n"
    "          <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)'}}>\n"
    "            System Status\n"
    "          </div>\n"
    "          <div style={{padding:16}}>\n"
    "            <div style={{fontSize:'12px',color:'var(--text-secondary)',marginBottom:12}}>\n"
    "              OILTRACE AI maritime investigation workstation is operational.\n"
    "              All pipeline stages available in Simulation Mode.\n"
    "            </div>\n"
    "            <div className=\"alert alert-info\" style={{marginBottom:12}}>\n"
    "              <span>ℹ</span>\n"
    "              <div style={{fontSize:'12px'}}>Running in <strong>SIMULATION MODE</strong>. All data is synthetic with seed 26143. Results are deterministic and reproducible.</div>\n"
    "            </div>\n"
    "            <div style={{fontSize:'11px',color:'var(--text-muted)',marginBottom:8,textTransform:'uppercase',letterSpacing:'0.06em',fontWeight:600}}>Quick Access</div>\n"
    "            {incidents[0] && [\n"
    "              ['Satellite Detection', '/incidents/'+incidents[0].id+'/detection'],\n"
    "              ['Drift / Hindcast', '/incidents/'+incidents[0].id+'/drift'],\n"
    "              ['Forecast', '/incidents/'+incidents[0].id+'/forecast'],\n"
    "              ['Vessel Investigation', '/incidents/'+incidents[0].id+'/vessels'],\n"
    "              ['Digital Twin', '/incidents/'+incidents[0].id+'/timeline'],\n"
    "              ['Investigation Report', '/incidents/'+incidents[0].id+'/report'],\n"
    "            ].map(([label,path]) => (\n"
    "              <div key={path as string} onClick={()=>navigate(path as string)}\n"
    "                style={{padding:'7px 10px',marginBottom:2,borderRadius:'var(--radius)',border:'1px solid var(--border)',cursor:'pointer',fontSize:'13px',color:'var(--text-secondary)',background:'var(--surface-1)'}}\n"
    "                onMouseEnter={e=>{e.currentTarget.style.background='var(--surface-2)';e.currentTarget.style.color='var(--text-primary)';}}\n"
    "                onMouseLeave={e=>{e.currentTarget.style.background='var(--surface-1)';e.currentTarget.style.color='var(--text-secondary)';}}\n"
    "              >{label as string}</div>\n"
    "            ))}\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

print("CommandCenter done")
