from pathlib import Path

def w(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {path}")

# ── DriftPage ─────────────────────────────────────────────────────────────────
w("frontend/src/pages/DriftPage.tsx", (
    "import React, { useState, useEffect } from 'react';\n"
    "import { useParams, useNavigate } from 'react-router-dom';\n"
    "import { fetchSpill, fetchEnvironment, runHindcast } from '../services/api';\n"
    "import { useHindcast, useEnvironment } from '../hooks/useSpill';\n"
    "import InvestigationMap from '../map/InvestigationMap';\n"
    "import LayerControl from '../components/LayerControl';\n"
    "import ProvenanceBadge from '../components/ProvenanceBadge';\n"
    "import { LoadingState, ErrorState, UnavailableState } from '../components/StateComponents';\n\n"
    "export default function DriftPage() {\n"
    "  const { id } = useParams<{id:string}>();\n"
    "  const [spill, setSpill] = useState<any>(null);\n"
    "  const [running, setRunning] = useState(false);\n"
    "  const [envFields, setEnvFields] = useState<any[]>([]);\n"
    "  const { hindcast, loading: hLoading, error: hError, notFound, refetch } = useHindcast(id||null);\n\n"
    "  useEffect(() => {\n"
    "    if (!id) return;\n"
    "    fetchSpill(id).then(setSpill).catch(console.error);\n"
    "    fetchEnvironment(id).then(setEnvFields).catch(console.error);\n"
    "  }, [id]);\n\n"
    "  const handleRunHindcast = async () => {\n"
    "    if (!id) return;\n"
    "    setRunning(true);\n"
    "    try { await runHindcast(id); refetch(); } catch(e) { console.error(e); }\n"
    "    finally { setRunning(false); }\n"
    "  };\n\n"
    "  const currentField = envFields.find(f=>f.field_type==='current');\n"
    "  const windField = envFields.find(f=>f.field_type==='wind');\n"
    "  const currentPt = currentField?.field_data?.points?.[12];\n"
    "  const windPt = windField?.field_data?.points?.[12];\n"
    "  const currentSpeed = currentPt ? Math.sqrt(currentPt.current_u**2 + currentPt.current_v**2) : null;\n"
    "  const windSpeed = windPt ? Math.sqrt(windPt.wind_u**2 + windPt.wind_v**2) : null;\n\n"
    "  return (\n"
    "    <div style={{display:'flex',flexDirection:'column',height:'100%',overflow:'hidden'}}>\n"
    "      <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'var(--surface-1)',flexShrink:0}}>\n"
    "        <div>\n"
    "          <div style={{fontSize:'15px',fontWeight:600}}>{id} — Drift Reconstruction / Hindcast</div>\n"
    "          <div style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>Backward particle integration &bull; RK4 &bull; Multi-particle ensemble</div>\n"
    "        </div>\n"
    "        <div style={{display:'flex',gap:8,alignItems:'center'}}>\n"
    "          {!hindcast && !hLoading && (\n"
    "            <button className=\"btn btn-primary\" onClick={handleRunHindcast} disabled={running}>\n"
    "              {running ? 'Running...' : 'Run Hindcast'}\n"
    "            </button>\n"
    "          )}\n"
    "          <ProvenanceBadge provenance=\"reconstructed\" />\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style={{display:'grid',gridTemplateColumns:'260px 1fr 300px',flex:1,overflow:'hidden'}}>\n"
    "        {/* Left: Environment panel */}\n"
    "        <div style={{borderRight:'1px solid var(--border)',background:'var(--bg-secondary)',overflow:'auto'}}>\n"
    "          <div style={{padding:'10px 12px',borderBottom:'1px solid var(--border)',fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)'}}>\n"
    "            Environmental Data\n"
    "          </div>\n"
    "          <div style={{padding:12}}>\n"
    "            <div style={{marginBottom:12}}>\n"
    "              <div style={{fontSize:'11px',color:'var(--text-muted)',marginBottom:6,textTransform:'uppercase',letterSpacing:'0.06em'}}>Ocean Current</div>\n"
    "              {currentField ? (\n"
    "                <div>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',padding:'3px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>Speed (center)</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'12px'}}>{currentSpeed?.toFixed(3)} m/s</span>\n"
    "                  </div>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',padding:'3px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>U component</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'12px'}}>{currentPt?.current_u?.toFixed(4)} m/s E</span>\n"
    "                  </div>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',padding:'3px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>V component</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'12px'}}>{currentPt?.current_v?.toFixed(4)} m/s N</span>\n"
    "                  </div>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',padding:'3px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>Source</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'11px',color:'var(--synthetic)'}}>{currentField.source}</span>\n"
    "                  </div>\n"
    "                </div>\n"
    "              ) : <div style={{fontSize:'12px',color:'var(--text-muted)'}}>Unavailable</div>}\n"
    "            </div>\n"
    "            <div style={{marginBottom:12}}>\n"
    "              <div style={{fontSize:'11px',color:'var(--text-muted)',marginBottom:6,textTransform:'uppercase',letterSpacing:'0.06em'}}>Wind (ERA5)</div>\n"
    "              {windField ? (\n"
    "                <div>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',padding:'3px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>Speed (center)</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'12px'}}>{windSpeed?.toFixed(2)} m/s</span>\n"
    "                  </div>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',padding:'3px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>U10</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'12px'}}>{windPt?.wind_u?.toFixed(3)} m/s E</span>\n"
    "                  </div>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',padding:'3px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>V10</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'12px'}}>{windPt?.wind_v?.toFixed(3)} m/s N</span>\n"
    "                  </div>\n"
    "                  <div style={{display:'flex',justifyContent:'space-between',padding:'3px 0'}}>\n"
    "                    <span style={{fontSize:'12px',color:'var(--text-muted)'}}>Source</span>\n"
    "                    <span style={{fontFamily:'var(--font-mono)',fontSize:'11px',color:'var(--synthetic)'}}>{windField.source}</span>\n"
    "                  </div>\n"
    "                </div>\n"
    "              ) : <div style={{fontSize:'12px',color:'var(--text-muted)'}}>Unavailable</div>}\n"
    "            </div>\n"
    "            {envFields.length>0 && (\n"
    "              <div className=\"alert alert-warning\">\n"
    "                <span>⚠</span>\n"
    "                <div style={{fontSize:'11px'}}>{currentField?.field_data?.note || 'Environmental data is synthetic. Not real ocean/wind data.'}</div>\n"
    "              </div>\n"
    "            )}\n"
    "          </div>\n"
    "        </div>\n"
    "        {/* Center: Map */}\n"
    "        {hLoading ? <LoadingState message=\"Loading hindcast...\" /> : (\n"
    "          <InvestigationMap spill={spill} hindcast={hindcast}>\n"
    "            <LayerControl />\n"
    "            {!hindcast && !hLoading && (\n"
    "              <div style={{position:'absolute',top:'50%',left:'50%',transform:'translate(-50%,-50%)',background:'var(--surface-1)',border:'1px solid var(--border)',borderRadius:'var(--radius-md)',padding:'20px 24px',textAlign:'center'}}>\n"
    "                <div style={{fontSize:'13px',color:'var(--text-secondary)',marginBottom:12}}>No hindcast computed yet</div>\n"
    "                <button className=\"btn btn-primary\" onClick={handleRunHindcast} disabled={running}>{running?'Running...':'Run Hindcast'}</button>\n"
    "              </div>\n"
    "            )}\n"
    "          </InvestigationMap>\n"
    "        )}\n"
    "        {/* Right: Hindcast results */}\n"
    "        <div style={{borderLeft:'1px solid var(--border)',background:'var(--bg-secondary)',overflow:'auto'}}>\n"
    "          <div style={{padding:'10px 12px',borderBottom:'1px solid var(--border)',fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)'}}>\n"
    "            Origin Estimate\n"
    "          </div>\n"
    "          {hindcast ? (\n"
    "            <div style={{padding:12}}>\n"
    "              <div className=\"alert alert-info\" style={{marginBottom:12}}>\n"
    "                <div style={{fontSize:'12px'}}>Estimated Origin Region\u2014 not an exact point. Spatial and temporal uncertainty shown below.</div>\n"
    "              </div>\n"
    "              {[\n"
    "                ['Origin Lat', hindcast.origin_lat?.toFixed(6)+'\xb0N'],\n"
    "                ['Origin Lon', hindcast.origin_lon?.toFixed(6)+'\xb0E'],\n"
    "                ['Estimated Release Window', hindcast.origin_time_estimate?.slice(0,19)+' UTC'],\n"
    "                ['Temporal Uncertainty', '\xb1'+hindcast.origin_time_uncertainty_h+' h'],\n"
    "                ['Spatial Uncertainty', hindcast.spatial_uncertainty_km?.toFixed(2)+' km'],\n"
    "                ['Particle Count', hindcast.particle_count],\n"
    "                ['Integration Method', hindcast.integration_method],\n"
    "                ['Windage Coefficient', hindcast.windage_coefficient+' (\\u03b1)'],\n"
    "                ['Timestep', hindcast.timestep_min+' min'],\n"
    "                ['Hindcast Duration', (hindcast.hindcast_hours || hindcast.integration_hours)+' h'],\n"
    "                ['Provenance', 'RECONSTRUCTED / SYNTHETIC'],\n"
    "              ].map(([k,v]) => (\n"
    "                <div key={k} style={{display:'flex',justifyContent:'space-between',padding:'4px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                  <span style={{fontSize:'12px',color:'var(--text-muted)'}}>{k}</span>\n"
    "                  <span style={{fontSize:'12px',fontFamily:'var(--font-mono)',color: String(v).includes('RECONSTRUCTED')?'var(--reconstructed)':'var(--text-primary)'}}>{v}</span>\n"
    "                </div>\n"
    "              ))}\n"
    "            </div>\n"
    "          ) : (\n"
    "            <div style={{padding:16}}>\n"
    "              <UnavailableState title=\"No Hindcast\" message=\"Click 'Run Hindcast' to compute the backward particle integration and estimate the probable origin region.\" />\n"
    "            </div>\n"
    "          )}\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

print("DriftPage done")
