from pathlib import Path

def w(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {path}")

# ── Detection page ────────────────────────────────────────────────────────────
w("frontend/src/pages/DetectionPage.tsx", (
    "import React, { useEffect, useState } from 'react';\n"
    "import { useParams } from 'react-router-dom';\n"
    "import { fetchSpill, fetchSpillImage } from '../services/api';\n"
    "import ProvenanceBadge from '../components/ProvenanceBadge';\n"
    "import ProcessingPipeline from '../components/ProcessingPipeline';\n"
    "import SarLimitation from '../components/SarLimitation';\n"
    "import { LoadingState, ErrorState } from '../components/StateComponents';\n\n"
    "export default function DetectionPage() {\n"
    "  const { id } = useParams<{id:string}>();\n"
    "  const [spill, setSpill] = useState<any>(null);\n"
    "  const [image, setImage] = useState<any>(null);\n"
    "  const [loading, setLoading] = useState(true);\n"
    "  const [error, setError] = useState<string|null>(null);\n\n"
    "  useEffect(() => {\n"
    "    if (!id) return;\n"
    "    Promise.all([fetchSpill(id), fetchSpillImage(id)])\n"
    "      .then(([sp,img]) => { setSpill(sp); setImage(img); })\n"
    "      .catch(e=>setError(e.message)).finally(()=>setLoading(false));\n"
    "  }, [id]);\n\n"
    "  if (loading) return <LoadingState message=\"Loading detection data...\" />;\n"
    "  if (error) return <ErrorState message={error} />;\n"
    "  if (!spill) return <ErrorState message=\"Spill not found\" />;\n\n"
    "  const stages = [\n"
    "    { label: '1. Scene uploaded', status: 'complete' as const, detail: image?.filename?.slice(0,40)+'...' },\n"
    "    { label: '2. Metadata validated', status: 'complete' as const, detail: 'CRS: '+image?.crs+', '+image?.resolution_m+'m/px' },\n"
    "    { label: '3. SAR preprocessing', status: 'complete' as const, detail: 'v'+spill?.preprocessing_version },\n"
    "    { label: '4. Model inference', status: 'complete' as const, detail: spill?.model_version+' [PRECOMPUTED / DEMO]' },\n"
    "    { label: '5. Mask generated', status: 'complete' as const, detail: 'threshold: '+spill?.model_threshold },\n"
    "    { label: '6. Geometry extracted', status: 'complete' as const, detail: spill?.area_km2?.toFixed(3)+' km\xb2' },\n"
    "    { label: '7. Characterization complete', status: 'complete' as const, detail: 'compactness: '+spill?.compactness?.toFixed(4) },\n"
    "  ];\n\n"
    "  const metrics = [\n"
    "    ['Detection Confidence', (spill.detection_confidence*100).toFixed(1)+'%'],\n"
    "    ['Detected Class', spill.detected_class],\n"
    "    ['Spill Area', spill.area_km2?.toFixed(3)+' km\xb2'],\n"
    "    ['Perimeter', spill.perimeter_km?.toFixed(3)+' km'],\n"
    "    ['Length', spill.length_km?.toFixed(3)+' km'],\n"
    "    ['Width', spill.width_km?.toFixed(3)+' km'],\n"
    "    ['Orientation', spill.orientation_deg?.toFixed(1)+'\xb0'],\n"
    "    ['Compactness (4\u03c0A/P\xb2)', spill.compactness?.toFixed(6)],\n"
    "    ['Centroid Lat', spill.centroid_geojson?.coordinates?.[1]?.toFixed(6)],\n"
    "    ['Centroid Lon', spill.centroid_geojson?.coordinates?.[0]?.toFixed(6)],\n"
    "    ['Acquisition Time', spill.satellite_acquisition_time?.slice(0,19)+' UTC'],\n"
    "    ['CRS', image?.crs],\n"
    "    ['Resolution', image?.resolution_m+'m/px'],\n"
    "    ['Satellite', image?.satellite_name],\n"
    "    ['Model Version', spill.model_version],\n"
    "    ['Preprocessing', spill.preprocessing_version],\n"
    "    ['Threshold', spill.model_threshold],\n"
    "  ];\n\n"
    "  return (\n"
    "    <div style={{display:'flex',flexDirection:'column',height:'100%',overflow:'hidden'}}>\n"
    "      <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'var(--surface-1)',flexShrink:0}}>\n"
    "        <div>\n"
    "          <div style={{fontSize:'15px',fontWeight:600}}>{id} — Satellite Detection</div>\n"
    "          <div style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>{spill.incident_name}</div>\n"
    "        </div>\n"
    "        <div style={{display:'flex',gap:8,alignItems:'center'}}>\n"
    "          <ProvenanceBadge provenance={spill.provenance} />\n"
    "          <span style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>class: {spill.detected_class}</span>\n"
    "          <span style={{fontSize:'15px',fontFamily:'var(--font-mono)',fontWeight:600,color:'var(--accent)'}}>{(spill.detection_confidence*100).toFixed(1)}% conf</span>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div style={{flex:1,display:'grid',gridTemplateColumns:'1fr 280px',overflow:'hidden'}}>\n"
    "        {/* SAR Image placeholder + overlay */}\n"
    "        <div style={{background:'#060A0F',position:'relative',overflow:'hidden',borderRight:'1px solid var(--border)',display:'flex',flexDirection:'column'}}>\n"
    "          <div style={{padding:'8px 12px',borderBottom:'1px solid var(--border)',display:'flex',gap:8,alignItems:'center',background:'var(--surface-1)',flexShrink:0}}>\n"
    "            <ProvenanceBadge provenance=\"synthetic\" />\n"
    "            <span style={{fontSize:'11px',color:'var(--text-muted)'}}>PRECOMPUTED / DEMO SAR — Not from real satellite acquisition</span>\n"
    "          </div>\n"
    "          {/* Synthetic SAR visualization */}\n"
    "          <div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',position:'relative'}}>\n"
    "            <svg width=\"100%\" height=\"100%\" viewBox=\"0 0 800 600\" style={{position:'absolute',top:0,left:0}}>\n"
    "              <rect width=\"800\" height=\"600\" fill=\"#070C12\" />\n"
    "              {/* Noise background */}\n"
    "              {Array.from({length:2000}).map((_,i) => {\n"
    "                const x=(i*137.5)%800,y=(i*73.3)%600,v=0.1+((i*31)%10)/30;\n"
    "                return <rect key={i} x={x} y={y} width=\"2\" height=\"2\" fill={'rgba(100,140,180,'+v+')'} />;\n"
    "              })}\n"
    "              {/* Dark region representing potential slick */}\n"
    "              <ellipse cx=\"420\" cy=\"320\" rx=\"140\" ry=\"75\" fill=\"rgba(0,0,0,0.7)\" opacity=\"0.8\" />\n"
    "              {/* Oil outline (detection result) */}\n"
    "              <ellipse cx=\"420\" cy=\"320\" rx=\"140\" ry=\"75\" fill=\"none\" stroke=\"#FFB020\" strokeWidth=\"2\" strokeDasharray=\"8 4\" opacity=\"0.9\" />\n"
    "              {/* Centroid marker */}\n"
    "              <circle cx=\"420\" cy=\"320\" r=\"6\" fill=\"#F97316\" stroke=\"white\" strokeWidth=\"2\" />\n"
    "              <text x=\"432\" y=\"316\" fill=\"#FFB020\" fontSize=\"12\" fontFamily=\"monospace\">SPILL CENTROID</text>\n"
    "              {/* Scale bar */}\n"
    "              <line x1=\"40\" y1=\"560\" x2=\"120\" y2=\"560\" stroke=\"white\" strokeWidth=\"2\" />\n"
    "              <text x=\"40\" y=\"555\" fill=\"white\" fontSize=\"10\" fontFamily=\"monospace\">~5km</text>\n"
    "              {/* Coordinate annotations */}\n"
    "              <text x=\"10\" y=\"20\" fill=\"rgba(167,176,186,0.7)\" fontSize=\"10\" fontFamily=\"monospace\">15.42\xb0N 72.68\xb0E</text>\n"
    "              <text x=\"10\" y=\"580\" fill=\"rgba(167,176,186,0.7)\" fontSize=\"10\" fontFamily=\"monospace\">Sentinel-1A | VV+VH | 10m/px | 2024-03-15 06:00 UTC</text>\n"
    "              <text x=\"580\" y=\"20\" fill=\"rgba(200,164,93,0.8)\" fontSize=\"11\" fontFamily=\"monospace\" fontWeight=\"600\">DEMO RENDER</text>\n"
    "            </svg>\n"
    "          </div>\n"
    "          <div style={{padding:'8px 12px',borderTop:'1px solid var(--border)',background:'var(--surface-1)',flexShrink:0}}>\n"
    "            <SarLimitation />\n"
    "          </div>\n"
    "        </div>\n"
    "        {/* Right panel: metrics + pipeline */}\n"
    "        <div style={{overflow:'auto',display:'flex',flexDirection:'column',gap:0}}>\n"
    "          <div style={{padding:'10px 12px',borderBottom:'1px solid var(--border)',fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)',background:'var(--surface-1)',flexShrink:0}}>Detection Metrics</div>\n"
    "          <div style={{padding:'12px',flex:1,overflow:'auto'}}>\n"
    "            {metrics.map(([k,v]) => (\n"
    "              <div key={k} style={{display:'flex',justifyContent:'space-between',padding:'4px 0',borderBottom:'1px solid var(--border)'}}>\n"
    "                <span style={{fontSize:'12px',color:'var(--text-muted)'}}>{k}</span>\n"
    "                <span style={{fontSize:'12px',fontFamily:'var(--font-mono)',color:'var(--text-primary)'}}>{v}</span>\n"
    "              </div>\n"
    "            ))}\n"
    "          </div>\n"
    "          <div style={{borderTop:'1px solid var(--border)',padding:'10px 12px',background:'var(--surface-1)',flexShrink:0}}>\n"
    "            <div style={{fontSize:'11px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.06em',color:'var(--text-muted)',marginBottom:8}}>Processing Pipeline</div>\n"
    "            <ProcessingPipeline stages={stages} />\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

print("DetectionPage done")
