from pathlib import Path

def w(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    print(f"wrote {path}")

# ── ProvenanceBadge ──────────────────────────────────────────────────────────
w("frontend/src/components/ProvenanceBadge.tsx", (
    "import React from 'react';\n\n"
    "type P = 'observed'|'reconstructed'|'predicted'|'synthetic';\n"
    "const LABELS: Record<P,string> = {observed:'OBSERVED',reconstructed:'RECONSTRUCTED',predicted:'PREDICTED',synthetic:'SYNTHETIC'};\n"
    "export default function ProvenanceBadge({ provenance }: { provenance: string }) {\n"
    "  const p = (provenance||'synthetic') as P;\n"
    "  return <span className={'tag tag-'+p}>{LABELS[p]||p.toUpperCase()}</span>;\n"
    "}\n"
))

# ── ProcessingPipeline ───────────────────────────────────────────────────────
w("frontend/src/components/ProcessingPipeline.tsx", (
    "import React from 'react';\n\n"
    "type Stage = { label: string; status: 'complete'|'processing'|'waiting'|'error'; detail?: string; };\n"
    "export default function ProcessingPipeline({ stages }: { stages: Stage[] }) {\n"
    "  const icons = { complete: '✓', processing: '●', waiting: '○', error: '✗' };\n"
    "  return (\n"
    "    <div className=\"pipeline\">\n"
    "      {stages.map((s,i) => (\n"
    "        <div key={i} className={'pipeline-stage pipeline-stage--'+s.status}>\n"
    "          <div className=\"pipeline-stage__icon\">{icons[s.status]}</div>\n"
    "          <span className=\"pipeline-stage__label\">{s.label}</span>\n"
    "          {s.detail && <span style={{fontSize:'11px',color:'var(--text-muted)',fontFamily:'var(--font-mono)'}}>{s.detail}</span>}\n"
    "        </div>\n"
    "      ))}\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

# ── KpiStrip ─────────────────────────────────────────────────────────────────
w("frontend/src/components/KpiStrip.tsx", (
    "import React from 'react';\n\n"
    "interface KpiProps { value: string|number; label: string; source?: string; color?: string; }\n"
    "function KpiCard({ value, label, source, color }: KpiProps) {\n"
    "  return (\n"
    "    <div className=\"kpi-card\">\n"
    "      <div className=\"kpi-card__value\" style={color?{color}:{}}>{value}</div>\n"
    "      <div className=\"kpi-card__label\">{label}</div>\n"
    "      {source && <div className=\"kpi-card__source\">{source}</div>}\n"
    "    </div>\n"
    "  );\n"
    "}\n\n"
    "interface KpiStripProps {\n"
    "  activeIncidents: number; analyzedScenes: number; analyzedVessels: number; highPriority: number;\n"
    "}\n"
    "export default function KpiStrip({ activeIncidents, analyzedScenes, analyzedVessels, highPriority }: KpiStripProps) {\n"
    "  return (\n"
    "    <div className=\"kpi-strip\">\n"
    "      <KpiCard value={activeIncidents} label=\"Active Incidents\" source=\"oil_spills table\" />\n"
    "      <KpiCard value={analyzedScenes} label=\"Analyzed Scenes\" source=\"satellite_images table\" />\n"
    "      <KpiCard value={analyzedVessels} label=\"Analyzed Vessels\" source=\"vessels table\" />\n"
    "      <KpiCard value={highPriority} label=\"High Priority Cases\" source=\"severity=high|critical\" color=\"var(--status-error)\" />\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

# ── LayerControl ─────────────────────────────────────────────────────────────
w("frontend/src/components/LayerControl.tsx", (
    "import React, { useState } from 'react';\n"
    "import { useStore } from '../state/store';\n"
    "import type { LayerKey } from '../state/store';\n\n"
    "const LAYERS: Array<{ key: LayerKey; label: string; color: string; }> = [\n"
    "  { key: 'slickGeometry',  label: 'Slick Geometry',     color: '#F59E0B' },\n"
    "  { key: 'detectionMask',  label: 'Detection Mask',     color: '#FFB020' },\n"
    "  { key: 'originRegion',   label: 'Origin Region',      color: '#7C8FA6' },\n"
    "  { key: 'hindcast',       label: 'Hindcast Particles',  color: '#6F879C' },\n"
    "  { key: 'forecast',       label: 'Forecast Particles',  color: '#A8B7C5' },\n"
    "  { key: 'currentVectors', label: 'Current Vectors',    color: '#3FA7D6' },\n"
    "  { key: 'windVectors',    label: 'Wind Vectors',       color: '#5E91B3' },\n"
    "  { key: 'aisVessels',     label: 'AIS Vessels',        color: '#E6EAEE' },\n"
    "  { key: 'vesselTracks',   label: 'Vessel Tracks',      color: '#A7B0BA' },\n"
    "  { key: 'candidateVessel',label: 'Candidate Vessel',   color: '#D97706' },\n"
    "  { key: 'uncertainty',    label: 'Uncertainty',        color: '#8FA3B8' },\n"
    "];\n\n"
    "export default function LayerControl() {\n"
    "  const { layers, setLayer } = useStore();\n"
    "  const [open, setOpen] = useState(true);\n"
    "  return (\n"
    "    <div className=\"layer-control\">\n"
    "      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:open?8:0}}>\n"
    "        <span style={{fontSize:'10px',fontWeight:600,textTransform:'uppercase',letterSpacing:'0.08em',color:'var(--text-muted)'}}>Layers</span>\n"
    "        <button onClick={()=>setOpen(!open)} className=\"btn-icon btn-ghost\" style={{padding:'2px 4px',fontSize:'10px'}}>{open?'▲':'▼'}</button>\n"
    "      </div>\n"
    "      {open && LAYERS.map(l => (\n"
    "        <label key={l.key} className=\"layer-toggle\">\n"
    "          <input type=\"checkbox\" checked={layers[l.key]} onChange={e=>setLayer(l.key,e.target.checked)} />\n"
    "          <span className=\"layer-toggle-swatch\" style={{background:l.color}}/>\n"
    "          <span>{l.label}</span>\n"
    "        </label>\n"
    "      ))}\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

# ── EvidenceBar ───────────────────────────────────────────────────────────────
w("frontend/src/components/EvidenceBar.tsx", (
    "import React from 'react';\n\n"
    "interface EvidenceBarProps {\n"
    "  label: string; rawValue: number; rawUnit: string;\n"
    "  normalized: number; weight: number; contribution: number;\n"
    "}\n"
    "export default function EvidenceBar({ label, rawValue, rawUnit, normalized, weight, contribution }: EvidenceBarProps) {\n"
    "  return (\n"
    "    <div className=\"evidence-bar\">\n"
    "      <div className=\"evidence-bar__header\">\n"
    "        <span className=\"evidence-bar__label\">{label}</span>\n"
    "        <span className=\"evidence-bar__values mono\">{rawValue.toFixed(2)} {rawUnit} | norm: {normalized.toFixed(3)} | wt: {(weight*100).toFixed(0)}%</span>\n"
    "      </div>\n"
    "      <div className=\"evidence-bar__track\">\n"
    "        <div className=\"evidence-bar__fill\" style={{width:(normalized*100)+'%'}} />\n"
    "      </div>\n"
    "      <div className=\"evidence-bar__contribution\">Contribution: {contribution.toFixed(4)}</div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

# ── FilteringFunnel ───────────────────────────────────────────────────────────
w("frontend/src/components/FilteringFunnel.tsx", (
    "import React from 'react';\n\n"
    "interface FunnelStage { label: string; count: number; removed?: number; config?: string; active?: boolean; }\n"
    "export default function FilteringFunnel({ stages }: { stages: FunnelStage[] }) {\n"
    "  return (\n"
    "    <div className=\"funnel\">\n"
    "      {stages.map((s,i) => (\n"
    "        <React.Fragment key={i}>\n"
    "          <div className={'funnel-stage' + (s.active?' funnel-stage--active':'')}>\n"
    "            <div>\n"
    "              <div className=\"funnel-stage__label\">{s.label}</div>\n"
    "              {s.config && <div style={{fontSize:'10px',color:'var(--text-disabled)',fontFamily:'var(--font-mono)'}}>{s.config}</div>}\n"
    "            </div>\n"
    "            <div style={{textAlign:'right'}}>\n"
    "              <div className=\"funnel-stage__count\">{s.count.toLocaleString()}</div>\n"
    "              {s.removed!=null && <div className=\"funnel-stage__removed\">-{s.removed}</div>}\n"
    "            </div>\n"
    "          </div>\n"
    "          {i<stages.length-1 && <div className=\"funnel-arrow\">↓</div>}\n"
    "        </React.Fragment>\n"
    "      ))}\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

# ── StateComponents ───────────────────────────────────────────────────────────
w("frontend/src/components/StateComponents.tsx", (
    "import React from 'react';\n\n"
    "export function LoadingState({ message='Loading...' }: { message?: string }) {\n"
    "  return <div className=\"state-container\"><div className=\"spinner\"/><div className=\"state-desc\">{message}</div></div>;\n"
    "}\n\n"
    "export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) {\n"
    "  return (\n"
    "    <div className=\"state-container\">\n"
    "      <div className=\"state-icon\">⚠</div>\n"
    "      <div className=\"state-title\">Error</div>\n"
    "      <div className=\"state-desc\">{message}</div>\n"
    "      {onRetry && <button className=\"btn btn-secondary btn-sm\" onClick={onRetry}>Retry</button>}\n"
    "    </div>\n"
    "  );\n"
    "}\n\n"
    "export function UnavailableState({ title, message }: { title: string; message: string }) {\n"
    "  return (\n"
    "    <div className=\"state-container\">\n"
    "      <div className=\"state-icon\">—</div>\n"
    "      <div className=\"state-title\">{title}</div>\n"
    "      <div className=\"state-desc\">{message}</div>\n"
    "    </div>\n"
    "  );\n"
    "}\n\n"
    "export function EmptyState({ title, message }: { title: string; message: string }) {\n"
    "  return (\n"
    "    <div className=\"state-container\">\n"
    "      <div className=\"state-icon\">◦</div>\n"
    "      <div className=\"state-title\">{title}</div>\n"
    "      <div className=\"state-desc\">{message}</div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

# ── SarLimitation note ────────────────────────────────────────────────────────
w("frontend/src/components/SarLimitation.tsx", (
    "import React from 'react';\n\n"
    "export default function SarLimitation() {\n"
    "  return (\n"
    "    <div className=\"alert alert-warning\" style={{borderRadius:'var(--radius)',fontSize:'12px'}}>\n"
    "      <span>⚠</span>\n"
    "      <div>\n"
    "        <strong>Scientific Limitation:</strong> SAR dark regions are not necessarily oil.\n"
    "        Low-wind zones, ship wakes, biogenic slicks and other phenomena can resemble oil.\n"
    "        Detection should be treated as investigative evidence requiring expert review.\n"
    "      </div>\n"
    "    </div>\n"
    "  );\n"
    "}\n"
))

print("all helper components done")
